<?php

namespace Demo\Domain\Model\Platform;

use ContainerGlWDYqc\getPropertyInfo_SerializerExtractorService;

class PlatformDto extends PlatformDtoAbstract
{
    public static function getPropertyMap(string $context = '', string $role = null): array
    {
        // Change collection visible fields
        if ($context == self::CONTEXT_COLLECTION) {
            return [
                'id' => 'id',
                'name' => 'name',
                'type' => 'type',
            ];
        }

        if ($context == self::CONTEXT_DETAILED) {
            return [
                'id' => 'id',
                'name' => 'name',
                'apiUrl' => 'apiUrl',
                'type' => 'type',
                'refresh_token' => 'refresh_token',
            ];
        }

        return parent::getPropertyMap($context, $role); // TODO: Change the autogenerated stub
    }
}
