<?php

namespace Demo\Infrastructure\Persistence\Doctrine;

use Doctrine\Persistence\ManagerRegistry;
use Ivoz\Core\Domain\Service\EntityPersisterInterface;
use Ivoz\Core\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository;
use Demo\Domain\Model\Administrator\Administrator;
use Demo\Domain\Model\Administrator\AdministratorRepository;
use Demo\Domain\Model\Administrator\AdministratorInterface;
use Demo\Domain\Model\Administrator\AdministratorDto;

/**
 * AdministratorDoctrineRepository
 *
 * This class was generated by ivoz:make:repositories command.
 * Add your own custom repository methods below.
 *
 * @extends DoctrineRepository<AdministratorInterface, AdministratorDto>
 */
class AdministratorDoctrineRepository extends DoctrineRepository implements AdministratorRepository
{
    public function __construct(
        ManagerRegistry $registry,
        EntityPersisterInterface $entityPersisterInterface,
    ) {
        parent::__construct(
            $registry,
            Administrator::class,
            $entityPersisterInterface
        );
    }

    public function findByUsername(string $username): ?AdministratorInterface
    {
        /** @var ?AdministratorInterface $administrator */
        $administrator = $this->findOneBy([
            'username' => $username,
        ]);

        return $administrator;
    }
}
