<?php

namespace Demo\Infrastructure\Persistence\Doctrine;

use Doctrine\Persistence\ManagerRegistry;
use Ivoz\Core\Domain\Service\EntityPersisterInterface;
use Ivoz\Core\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository;
use Demo\Domain\Model\Client\Client;
use Demo\Domain\Model\Client\ClientRepository;
use Demo\Domain\Model\Client\ClientInterface;
use Demo\Domain\Model\Client\ClientDto;

/**
 * ClientDoctrineRepository
 *
 * This class was generated by ivoz:make:repositories command.
 * Add your own custom repository methods below.
 *
 * @extends DoctrineRepository<ClientInterface, ClientDto>
 */
class ClientDoctrineRepository extends DoctrineRepository implements ClientRepository
{
    public function __construct(
        ManagerRegistry $registry,
        EntityPersisterInterface $entityPersisterInterface,
    ) {
        parent::__construct(
            $registry,
            Client::class,
            $entityPersisterInterface
        );
    }
}