<?php

namespace Demo\Infrastructure\Persistence\Doctrine;

use Doctrine\Persistence\ManagerRegistry;
use Ivoz\Core\Domain\Service\EntityPersisterInterface;
use Ivoz\Core\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository;
use Demo\Domain\Model\Platform\Platform;
use Demo\Domain\Model\Platform\PlatformRepository;
use Demo\Domain\Model\Platform\PlatformInterface;
use Demo\Domain\Model\Platform\PlatformDto;

/**
 * PlatformDoctrineRepository
 *
 * This class was generated by ivoz:make:repositories command.
 * Add your own custom repository methods below.
 *
 * @extends DoctrineRepository<PlatformInterface, PlatformDto>
 */
class PlatformDoctrineRepository extends DoctrineRepository implements PlatformRepository
{
    public function __construct(
        ManagerRegistry $registry,
        EntityPersisterInterface $entityPersisterInterface,
    ) {
        parent::__construct(
            $registry,
            Platform::class,
            $entityPersisterInterface
        );
    }
}