<?php

namespace Demo\Infrastructure\Persistence\Doctrine;

use Doctrine\Persistence\ManagerRegistry;
use Ivoz\Core\Domain\Service\EntityPersisterInterface;
use Ivoz\Core\Infrastructure\Persistence\Doctrine\Repository\DoctrineRepository;
use Demo\Domain\Model\Timezone\TimezoneRepository;
use Demo\Domain\Model\Timezone\TimezoneInterface;
use Demo\Domain\Model\Timezone\TimezoneDto;

/**
 * TimezoneDoctrineRepository
 *
 * This class was generated by ivoz:make:repositories command.
 * Add your own custom repository methods below.
 *
 * @extends DoctrineRepository<TimezoneInterface, TimezoneDto>
 */
class TimezoneDoctrineRepository extends DoctrineRepository implements TimezoneRepository
{
    public function __construct(
        ManagerRegistry $registry,
        EntityPersisterInterface $entityPersisterInterface,
    ) {
        parent::__construct(
            $registry,
            TimezoneRepository::class,
            $entityPersisterInterface
        );
    }
}
