imports:
    - { resource: "@ApiBundle/Resources/config/api_platform_base.yml" }

api_platform:
    title: 'Demo'
    version: 1.0
    collection:
        pagination:
            # The maximum number of items per page.
            maximum_items_per_page: 10000
    swagger:
        versions: [2]
    formats:
        png:
            mime_types: [ 'image/png' ]