name: Test app console

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json
      run: cd app/ && composer validate --strict

    - name: Install dependencies
      uses: php-actions/composer@v6

    - name: Install dependencies
      run: cd app/ && composer install --prefer-dist --no-progress

    - name: Validate app-console
      run: cd app/ && bin/console

