name: Test app console

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      
      uses: php-actions/composer@v6 
      working_dir: app/

    - name: Validate app-console
      run: bin/console
      working-directory: app/

